### ISSUE TITLE
Have you tried working with Modal dialogs with CSS transitions?

### ISSUE THREAD

**Issue by leolorenzoluis** [rastreus/FableStarter#2]
Stumbled upon your repo hoping someone can point me on how to do this in F# Fable with TailWindCSS. I'm trying to create a modal dialog that uses the TailWindCSS class names, but it looks like it requires additional work to make it work?

**Comment by rastreus** [comment]
You could use the Modal component from daisyUI: [https://daisyui.com/components/modal/](https://daisyui.com/components/modal/).
