### ISSUE TITLE
Questiion about debugging :)

### ISSUE THREAD

**Issue by marcingolenia** [rastreus/FableStarter#3]
Hi! feel free to close the issue right away! I just hoped to get some tips on how to enable debugging in F# files with Vite and VsCode ;) Any hints?

**Comment by rastreus** [comment]
I do **not** debug my frontend code with Visual Studio Code.

I use the following tools:

* Chrome DevTools debugger (source mapped F# files)
* [Elmish.Debugger](https://elmish.github.io/debugger/) with Redux DevTools extension
* Console print lines (`printfn`)
* [Mock Service Worker](https://mswjs.io) for integration testing and debugging
